const AUDIT_ACTIONS = {
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  WAITLIST_JOINED: "WAITLIST_JOINED",
  WAITLIST_PROMOTED: "WAITLIST_PROMOTED",
  SLOT_CREATED: "SLOT_CREATED",
  OUTCOME_UPDATED: "OUTCOME_UPDATED",
};

export default AUDIT_ACTIONS;
